### ISSUE TITLE
Detail: viruses, including SARS-CoV-2, do in fact recombine

### ISSUE THREAD

**Issue by jshoyer** [mccoy-lab/hgv_modules#6]
https://github.com/mccoy-lab/hgv_modules/blob/e4e336e66a49202549b2641143dc90a32b86257b/11-coronavirus/11-coronavirus.Rmd#L31

A quick search will show many excellent review articles on virus recombination and reassortment. The confusion may be related to the fact that viruses do not have meiosis.

All Pango lineages of SARS-CoV-2 that start with the letter ‘X’, including XBB.1.5, are high-confidence recombinants.

The point about how recombination complicates phylogenetic analysis is important. If students are interested in this I would recommend the following pdf slides and accompanying tutorial on detecting recombination: https://davidrasm.github.io/MolEpi/lectures/MolEpi.Recombination.2022.Lecture6.pdf

**Comment by stephaniemyan** [comment]
Thanks for the suggestion! I've edited the paragraph you referenced to discuss viral recombination. Thanks as well for linking these recombination slides.
